---
- name: Add emacs28
  ansible.builtin.apt_repository:
          repo: ppa:kelleyk/emacs
          become: yes

- name: Install Emacs28
  ansible.builtin.apt:
          name: emacs28-nativecomp
          state: present
          become: yes
