---
- name: Checking for existing install
  stat:
    path: "$HOME/.oh-my-zsh"
  register: install
  become: true

- name: Install Oh-My-ZSH 
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
