---
- name: Fix any broken installs
  ansible.builtin.apt:
    name: "*"
    state: fixed
  become: true
  when: ansible_distribution == "Pop!_OS"

- name: Wait until the lock file is removed
  ansible.builtin.wait_for:
    path: /var/lock/file/lock
    state: absent

- name: Full apt upgrade
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes
  become: true
  retries: 5
  delay: 2
  when: ansible_distribution == "Pop!_OS"

- name: Update All Packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: yes
  retries: 10
  delay: 5
  become: true
  when: ansible_distribution == "Pop!_OS"

- name: Add PopOS Nvidia Driver
  ansible.builtin.apt_repository:
    repo: ppa:system76-dev/stable
  become: true
  when: ansible_os_family == "Pop!_OS"

- name: Install System-76 Driver
  ansible.builtin.package:
    name: system76-driver
  become: true
  when: ansible_distribution == "Pop!_OS"
