---
- name: Python Packages Playbook
  become: yes
  hosts: localhost
  tasks:
    - name: install pip3
      ansible.builtin.apt:
       name: pip
       state: present

    - name: Install numpy
      ansible.builtin.pip:
       name: numpy
       name: pandas
       name: tensorflow
       name: torch
       name: lightgbm
       name: gleam
       name: shogun
       name: opencv-contrib-python
       name: scrapy
       name: scikit-learn
       name: matplotlib
       name: nltk
    
