---
- name: Fonts playbook
  become: yes
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Download Fonts
       ansible.builtin.apt:
         pkg:
         - fonts-hack-ttf
         - gconf2
         - gconf-service
         - fonts-powerline
         - powerline
         state: latest
