---
- name: ensure fonts directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.fonts"
    state: directory

- name: Hack exists
  shell: "ls {{ lookup('env', 'HOME') }}/.fonts/Hack*Nerd*Font*Complete*"
  register: hack_exists
  ignore_errors: yes

- name: Download Hack
  when: hack_exists is failed
  ansible.builtin.apt:
    name: fonts-hack-ttf
    state: present

- name: download gfon2
  ansible.builtin.apt:
   name: gconf2
   state: present
  become: yes

- name: Change the widget font to "Hack-Regular"
  community.general.gconftool2:
    key: "/desktop/gnome/interface/font_name"
    value_type: "string"
    value: "Hack-regular.tff"    
