---
- name: Add Emacs to repository
  ansible.builtin.apt_repository:
    repo: ppa:kelleyk/emacs
  become: true

- name: install pexpect
  ansible.builtin.pip:
    name: 
      - pexpect
  become: true

- name: Install required packages
  ansible.builtin.apt:
    pkg:
        - ripgrep
        - fd-find
        - emacs28
  become: true

- name: Go to home directory
  ansible.builtin.shell: cd $HOME

- name: clone DOOM emacs
  ansible.builtin.git:
    repo: 'https://github.com/hlissner/doom-emacs'
    dest: ~/.emacs.d

- name: Install Doom Emacs
  expect:
    command: bash -c "~/.emacs.d/bin/doom install"
    timeout: 600
    responses:
      "Generate an envvar file?": "y"
      "Download and install": "y"

- name: Run Doom Sync
  ansible.builtin.shell: ~/.emacs.d/bin/doom sync

- name: Run Doom Doctor
  ansible.builtin.shell: ~/.emacs.d/bin/doom doctor
