---
- name: Install default terminal software
  ansible.builtin.apt:
    pkg:
      - powerline
      - gconf-service
      - whois
      - emacs28
      - pip
      - fonts-hack-ttf
      - dos2unix
      - fonts-powerline
      - vim
      - zsh
      - tmux
      - wget
      - curl
      - cargo
      - bat
  become: true

- name: Go to home directory
  ansible.builtin.shell: cd $HOME

- name: clone DOOM emacs
  ansible.builtin.git:
    repo: 'https://github.com/hlissner/doom-emacs'
    dest: ~/.emacs.d

- name: Install Doom Emacs
  expect:
    command: bash -c "~/.emacs.d/bin/doom install"
    timeout: 600
    responses:
      "Generate an envvar file?": "y"
      "Download and install": "y"

- name: Run Doom Sync
  ansible.builtin.shell: ~/.emacs.d/bin/doom sync

- name: Run Doom Doctor
  ansible.builtin.shell: ~/.emacs.d/bin/doom doctor
    # - name: Cargo install exa
    #  ansible.builtin.shell: cargo install exa
    #  become: true
