---
- name: Add Emacs to repository
  ansible.builtin.apt_repository:
    repo: ppa:kelleyk/emacs
  become: true

- name: Install default terminal software
  ansible.builtin.apt:
    pkg:
      - powerline
      - gconf-service
      - whois
      - emacs28
      - pip
      - fonts-hack-ttf
      - dos2unix
      - fonts-powerline
      - vim
      - zsh
      - tmux
      - wget
      - curl
      - cargo
      - bat
      - fd-find
      - ripgrep
      - make
      - cmake
      - libtool
      - libvterm-dev
      - htop
      - gcc
      - g++
      - make
      - exa
      - snapd
  become: true

- name: Cargo installs bat
  ansible.builtin.shell: cargo install --locked bat

