---
- name: Install default terminal software
  ansible.builtin.apt:
    pkg:
      - powerline
      - gconf-service
      - whois
      - emacs28
      - pip
      - fonts-hack-ttf
      - dos2unix
      - fonts-powerline
      - vim
      - zsh
      - tmux
      - wget
      - curl
      - cargo
      - bat
      - fd-find
  become: true
