---
- name: Install nvm
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: Install default terminal software
  ansible.builtin.apt:
    pkg:
      - powerline
      - gconf-service
      - whois
      - emacs28
      - pip
      - fonts-hack-ttf
      - dos2unix
      - fonts-powerline
      - vim
      - zsh
      - tmux
      - wget
      - curl
      - cargo
      - bat
      - fd-find
      - ripgrep
      - make
      - cmake
      - libtool
      - libvterm-dev
      - htop
      - gcc
      - g++
      - make
      - npm
      - nodejs
      - neovim
      - exa
      - snapd
      - python3-neovim
  become: true

- name: Cargo installs bat
  ansible.builtin.shell: cargo install --locked bat
