---
- name: Install default terminal software
  ansible.builtin.apt:
    pkg:
      - powerline
      - gconf-service
      - whois
      - emacs28
      - pip
      - fonts-hack-ttf
      - dos2unix
      - fonts-powerline
      - vim
      - zsh
      - tmux
      - wget
      - curl
      - cargo
      - bat
      - exa
  become: true

- name: install pexpect via pip
  ansible.builtin.shell: pip install pexpect

- name: Go to home directory
  ansible.builtin.shell: cd $HOME

- name: clone DOOM emacs
  ansible.builtin.git:
    repo: 'https://github.com/hlissner/doom-emacs'
    dest: ~/.emacs.d

- name: Install Doom Emacs
  expect:
    command: bash -c "~/.emacs.d/bin/doom install"
    responses:
      'Generate an envvar file? \(see `doom help env` for details\) (y or n)': 'y'
      "Download and install all-the-icon's fonts? (y or n)": 'y'

- name: Run Doom Sync
  ansible.builtin.shell: ~/.emacs.d/bin/doom sync

- name: Run Doom Doctor
  ansible.builtin.shell: ~/.emacs.d/bin/doom doctor
